---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkasr-cli
  namespace: confluent-ldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: confluent
      app.kubernetes.io/name: kafkasr-cli
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: confluent
        app.kubernetes.io/name: kafkasr-cli
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      containers:
      - name: kafkasr-cli
        image: confluentinc/cp-schema-registry:7.0.1
        command: ["bash", "-c", "tail -F /dev/null"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 700m
            memory: 300Mi
          requests:
            cpu: 700m
            memory: 300Mi
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/os"
                operator: "In"
                values: ["linux"]
              - key: "kubernetes.io/arch"
                operator: "In"
                values: ["amd64"]
