---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-fargate-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "efs"
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0bb43e3e61a1843a7 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-fargate-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "efs"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-fargate-app
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /data/out; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-fargate-claim