---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-statefulset-shared-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: efs-statefulset-shared-app
spec:
  selector:
    matchLabels:
      app: efs-statefulset-shared-app
  serviceName: efs-statefulset-shared-app
  replicas: 3
  template:
    metadata:
      labels:
        app: efs-statefulset-shared-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: linux
        image: centos
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo ${POD_NAME}: $(date -u) >> /data/out; sleep 5; done"]
        volumeMounts:
        - name: efs-storage
          mountPath: /data
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-statefulset-shared-claim