---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-sc1-readwriteonce-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc1
  resources:
    requests:
      storage: 125Gi # minimum storage volume for sc1
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-sc1-app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-sc1-readwriteonce-claim