---
apiVersion: v1
kind: Secret
metadata:
  name: controlcenter-credentials
  namespace: confluent-ldap
  labels:
    app.kubernetes.io/instance: confluent
type: Opaque
stringData:
  credentials.properties: |-
    username=${CONTROLCENTER_USERNAME}
    password=${CONTROLCENTER_PASSWORD}
