---
apiVersion: v1
kind: Secret
metadata:
  name: schemaregistry-credentials
  namespace: confluent-ldap
  labels:
    app.kubernetes.io/instance: confluent
type: Opaque
stringData:
  credentials.properties: |-
    username=${SCHEMAREGISTRY_USERNAME}
    password=${SCHEMAREGISTRY_PASSWORD}
