---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  labels:
    app.kubernetes.io/instance: confluent
    app.kubernetes.io/name: kafka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    app.kubernetes.io/instance: confluent
    app.kubernetes.io/name: kafka
spec:
  containers:
  - name: kafka
    image: confluentinc/cp-kafka:7.0.1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi
    env:
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper:2181"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka:9092"
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
      value: "1"
    - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_HEAP_OPTS
      value: "-Xmx384M -Xms384M"
    ports:
    - containerPort: 9092
      name: kafka
    volumeMounts:
    - name: data
      mountPath: /var/lib/kafka
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: kafka-data
  securityContext:
    fsGroup: 1000
  enableServiceLinks: false
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/instance: confluent
    app.kubernetes.io/name: kafka
spec:
  ports:
  - name: kafka
    port: 9092
    targetPort: kafka
    protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: confluent
    app.kubernetes.io/name: kafka