---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-proxy-letuscode
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ldap-proxy-letuscode
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ldap-proxy-letuscode
    spec:
      containers:
      - image: envoyproxy/envoy:v1.18-latest
        imagePullPolicy: Always
        name: envoy
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
          - containerPort: 1389
            name: ldap
        volumeMounts:
          - name: ldap-proxy-letuscode
            mountPath: /etc/envoy/envoy.yaml
            subPath: envoy.yaml
      volumes:
        - name: ldap-proxy-letuscode
          configMap:
            name: ldap-proxy-letuscode
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: "kubernetes.io/arch"
                operator: "In"
                values: ["arm64"]
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/os"
                operator: "In"
                values: ["linux"]
              - key: "kubernetes.io/arch"
                operator: "In"
                values: ["amd64", "arm64"]
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-proxy-letuscode
spec:
  ports:
    - name: ldap
      port: 389
      targetPort: ldap
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ldap-proxy-letuscode
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-proxy-letuscode
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 1389
        filter_chains:
        - filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: tcp
              cluster: ldap
      clusters:
      - name: ldap
        connect_timeout: 10s
        type: strict_dns
        lb_policy: round_robin
        load_assignment:
          cluster_name: ldap
          endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 10.0.3.5
                      port_value: 389