kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc1
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: sc1