---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 5
  containers:
  - name: dnsutils
    image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
    command: ["bash", "-c", "tail -F /dev/null"]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 100Mi
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: "kubernetes.io/arch"
            operator: "In"
            values: ["arm64"]
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.io/os"
            operator: "In"
            values: ["linux"]
          - key: "kubernetes.io/arch"
            operator: "In"
            values: ["amd64", "arm64"]