apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: ${EKS_NODE_GROUP_ROLE_ARN}
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: ${K8SADMIN_ROLE_ARN}
      username: admin
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::${ACCOUNT_ID}:user/ueisele
      username: admin