---
apiVersion: v1
kind: Secret
metadata:
  name: kafkarest-credentials
  namespace: confluent-kerberos
  labels:
    app.kubernetes.io/instance: confluent
type: Opaque
stringData:
  credentials.properties: |-
    username=${KAFKAREST_USERNAME}
    password=${KAFKAREST_PASSWORD}
