---
apiVersion: v1
kind: Secret
metadata:
  name: mds-token
  namespace: confluent-kerberos
  labels:
    app.kubernetes.io/instance: confluent
type: Opaque
data:
  mdsPublicKey.pem: $(cat keypair/public.pem | base64 -w0)
  mdsTokenKeyPair.pem: $(cat keypair/keypair.pem | base64 -w0)
