---
apiVersion: v1
kind: Secret
metadata:
  name: mds-credentials
  namespace: confluent-ldapproxy
  labels:
    app.kubernetes.io/instance: confluent
type: Opaque
stringData:
  credentials.properties: |-
    username=${MDS_USERNAME}
    password=${MDS_PASSWORD}
